# Generated by Django 4.2.2 on 2023-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_cart_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_info',
            name='price_total',
            field=models.IntegerField(default=0),
        ),
    ]
