# Generated by Django 4.2.2 on 2023-11-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_cart_info_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_info',
            name='price_total2',
            field=models.IntegerField(default=0),
        ),
    ]
