# Generated by Django 4.2.2 on 2023-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_alter_cart_info_price_total2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_info',
            name='price_total2',
            field=models.IntegerField(default=0),
        ),
    ]
